services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

